apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 80 # Service port (inside cluster)
      targetPort: 80 # Pod port (application port)
      nodePort: 30000
